##### Write a NumPy program to get the numpy version and show numpy build configuration.

In [11]:
import numpy as np
print(np.__version__)
# print(np.show_config())

1.22.3


##### Write a NumPy program to  get help on the add function. 

In [12]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

##### Write a NumPy program to test whether none of the elements of a given array is zero.

In [13]:
x = np.array([1, 2, 3, 4])
print(x)
print(np.all(x))
x = np.array([0,1, 2, 3, 4])
print(x)
print(np.all(x))

[1 2 3 4]
True
[0 1 2 3 4]
False


#####  Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [14]:
x = np.array([1, 0, 0, 0])
print(x)
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(x)
print(np.any(x))


[1 0 0 0]
True
[0 0 0 0]
False


##### Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [15]:
a = np.array([1, 0, np.nan, np.inf])
print(a)
print(np.isfinite(a))


[ 1.  0. nan inf]
[ True  True False False]


##### Write a NumPy program to test element-wise for positive or negative infinity.

In [16]:
a = np.array([1, 0 , np.nan, np.inf])
print(a)
print(np.isinf(a))

[ 1.  0. nan inf]
[False False False  True]


##### Write a NumPy program to test element-wise for NaN of a given array.

In [17]:
a = np.array([1, 0, np.nan, np.inf])
print(a)
print(np.isnan(a))


[ 1.  0. nan inf]
[False False  True False]


Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [18]:
a = np.array([1+1j, 1+0j, 2.5, 7, 9, 2j])
print(a)
print(np.iscomplex(a))
print(np.isreal(a))
print(np.isscalar(4.6))
print(np.isscalar([4.6]))


[1. +1.j 1. +0.j 2.5+0.j 7. +0.j 9. +0.j 0. +2.j]
[ True False False False False  True]
[False  True  True  True  True False]
True
False


Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

Note: The tolerance values are positive, typically very small numbers.  The
relative difference (`rtol` * abs(`b`)) and the absolute difference
`atol` are added together to compare against the absolute difference
between `a` and `b`.

In [19]:
# print(np.info(np.allclose))
print(np.allclose([1e10, 1e-7], [1.00001e10, 1e-8]))
print(np.allclose([1e10, 1e-8], [1.00001e10, 1e-9]))
print(np.allclose([1e10, 1e-8], [1.0001e10, 1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))


False
True
False
False
True


Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [21]:
x = np.array([3,6])
y = np.array([7,3])

print(x)
print(y)

print("Comparison -  Greater")
print(np.greater(x,y))


print("Comparison -  Greater Equal")
print(np.greater_equal(x,y))

print("Comparison -  Less")
print(np.less(x, y))

print("Comparison -  Less Equal")
print(np.less_equal(x, y))

[3 6]
[7 3]
Comparison -  Greater
[False  True]
Comparison -  Greater Equal
[False  True]
Comparison -  Less
[ True False]
Comparison -  Less Equal
[ True False]


Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [25]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print(x)
print(y)


print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))


[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.001001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
False


Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [29]:
x = np.array([1, 7, 13, 105])
print(x)

print("Size of Array", x.size * x.itemsize)


[  1   7  13 105]
Size of Array 32


Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [30]:
array = np.zeros(10)
print("An array of 10 zeros:")
print(array)
array = np.ones(10)
print("An array of 10 ones:")
print(array)
array = np.ones(10)*5
print("An array of 10 fives:")
print(array)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Write a NumPy program to create an array of the integers from 30 to70.

In [32]:
array = np.arange(30, 71)
print("Array of the integers from 30 to 70")
print(array)


Array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


Write a NumPy program to create an array of all the even integers from 30 to 70.

In [33]:
array = np.arange(30, 71, 2)
print("Array of all the even integers from 30 to 70")
print(array)


Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Write a NumPy program to create a 3x3 identity matrix.

In [34]:
array_2D = np.identity(3)
print('3x3 matrix:')
print(array_2D)


3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write a NumPy program to generate a random number between 0 and 1

In [52]:
rand_num = np.random.normal(0, 1, 2)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[0.91249236 0.24506455]


Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [53]:
rand_num = np.random.normal(0, 1, 15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)


15 random numbers from a standard normal distribution:
[ 0.02783662  0.38585182 -0.87769297  0.17995414 -0.75858178 -0.95012998
 -1.57491011 -0.94773752 -1.45284321 -1.38704445  2.36430932  2.7389492
 -1.82210174 -1.19020499 -2.43930182]


Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [54]:
v = np.arange(15, 55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])


Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


Write a NumPy program to create a 3X4 array using and iterate over it. 

In [57]:
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [58]:
v = np.linspace(10, 49, 5)
print("Length 10 with values evenly distributed between 5 and 50:")
print(v)


Length 10 with values evenly distributed between 5 and 50:
[10.   19.75 29.5  39.25 49.  ]


Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [59]:
x = np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [61]:
x = np.random.randint(0, 11, 5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)


Vector of length 5 filled with arbitrary integers from 0 to 10:
[5 2 8 1 7]


Write a NumPy program to multiply the values of two given vectors.

In [62]:
x = np.array([1, 8, 3, 5])
print("Vector-1")
print(x)
y = np.random.randint(0, 11, 4)
print("Vector-2")
print(y)
result = x * y
print("Multiply the values of two said vectors:")
print(result)


Vector-1
[1 8 3 5]
Vector-2
[1 4 7 6]
Multiply the values of two said vectors:
[ 1 32 21 30]


Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [63]:
m = np.arange(10, 22).reshape((3, 4))
print(m)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


Write a NumPy program to find the number of rows and columns of a given matrix.

In [64]:
m = np.arange(10, 22).reshape((3, 4))
print("Original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape)


Original matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows and columns of the said matrix:
(3, 4)


Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [65]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [68]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [69]:
x = np.diag([1, 2, 3, 4, 5])
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [72]:
x = np.zeros((4, 4))
print(x)
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [73]:
x = np.random.random((3, 3, 3))
print(x)

[[[0.71743963 0.41017008 0.56065457]
  [0.25187813 0.88175737 0.22690688]
  [0.35815759 0.85057995 0.0113102 ]]

 [[0.16824026 0.10734067 0.69501115]
  [0.04406321 0.61925911 0.25712463]
  [0.23652831 0.18416951 0.6655523 ]]

 [[0.09537045 0.86443015 0.9906574 ]
  [0.98487127 0.1101806  0.88402019]
  [0.46611055 0.70605466 0.65219156]]]


Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [76]:
x = np.array([[0, 1], [2, 3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


Write a NumPy program to compute the inner product of two given vectors.

In [77]:
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x, y))

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


Write a NumPy program to add a vector to each row of a given matrix.

In [79]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result = np.empty_like(m)
print(result)
for i in range(4):
  result[i, :] = m[i, :] + v
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)


Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


Write a NumPy program to save a given array to a binary file .

In [80]:
import os
a = np.arange(20)
np.save('temp_arra.npy', a)
print("Check if 'temp_arra.npy' exists or not?")
if os.path.exists('temp_arra.npy'):
    x2 = np.load('temp_arra.npy')
    print(np.array_equal(a, x2))


Check if 'temp_arra.npy' exists or not?
True


Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [81]:
x = np.arange(10)
y = np.arange(11, 20)
print("Original arrays:")
print(x)
print(y)
np.savez('temp_arra.npz', x=x, y=y)
print("Load arrays from the 'temp_arra.npz' file:")
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)


Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


Write a NumPy program to save a given array to a text file and load it.

In [82]:
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header)
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)


Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


Write a NumPy program to convert a given array into bytes, and load it as array.

In [83]:
a = np.array([1, 2, 3, 4, 5, 6])
print("Original array:")
print(a)
a_bytes = a.tobytes()
a2 = np.frombuffer(a_bytes, dtype=a.dtype)
print("After loading, content of the text file:")
print(a2)
print(np.array_equal(a, a2))


Original array:
[1 2 3 4 5 6]
After loading, content of the text file:
[1 2 3 4 5 6]
True


Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.

In [84]:
a = [[1, 2], [3, 4]]
x = np.array(a)
a2 = x.tolist()
print(a == a2)


True


Write a NumPy program to convert numpy dtypes to native python types.

In [85]:
print("numpy.float32 to python float")
x = np.float32(0)
print(type(x))
pyval = x.item()
print(type(pyval))


numpy.float32 to python float
<class 'numpy.float32'>
<class 'float'>


Write a NumPy program to add elements in a matrix. If an element in the matrix is 0, we will not add the element below this element

In [86]:
def sum_matrix_Elements(m):
    arra = np.array(m)
    element_sum = 0
    for p in range(len(arra)):
        for q in range(len(arra[p])):
            if arra[p][q] == 0 and p < len(arra)-1:
                arra[p+1][q] = 0
            element_sum += arra[p][q]
    return element_sum


m = [[1, 1, 0, 2],
     [0, 3, 0, 3],
     [1, 0, 4, 4]]
print("Original matrix:")
print(m)
print("Sum:")
print(sum_matrix_Elements(m))


Original matrix:
[[1, 1, 0, 2], [0, 3, 0, 3], [1, 0, 4, 4]]
Sum:
14


Write a NumPy program to find the missing data in a given array.

In [87]:
nums = np.array([[3, 2, np.nan, 1],
                 [10, 12, 10, 9],
                 [5, np.nan, 1, np.nan]])

print("Original array:")
print(nums)
print("\nFind the missing data of the said array:")
print(np.isnan(nums))


Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [89]:
nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.4999999999, 1.500000000, 0.2])
np.set_printoptions(precision=15)
print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)
nums1 = np.array([0.5, 1.5, 0.23])
nums2 = np.array([0.4999999999, 1.5000000001, 0.23])
print("\nOriginal arrays:")
np.set_printoptions(precision=15)
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(np.equal(nums1, nums2))


Original arrays:
[0.5 1.5 0.2]
[0.4999999999 1.5          0.2         ]

Test said two arrays are equal (element wise) or not:?
[False  True  True]

Original arrays:
[0.5  1.5  0.23]
[0.4999999999 1.5000000001 0.23        ]

Test said two arrays are equal (element wise) or not:?
[False False  True]


Write a NumPy program to create one-dimensional array of single, two and three digit numbers

In [90]:
nums = np.arange(1, 21)
print("One-dimensional array of single digit numbers:")
print(nums)
nums = np.arange(10, 21)
print("\nOne-dimensional array of two digit numbers:")
print(nums)
nums = np.arange(100, 201)
print("\nOne-dimensional array of three digit numbers:")
print(nums)


One-dimensional array of single digit numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

One-dimensional array of two digit numbers:
[10 11 12 13 14 15 16 17 18 19 20]

One-dimensional array of three digit numbers:
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


Write a NumPy program to create a two-dimensional array of specified format.

In [91]:
print("Create an array of shape (15,10):")
print("Command-1")
print(np.arange(1, 151).reshape(15, 10))
print("\nCommand-2")
print(np.arange(1, 151).reshape(-1, 10))
print("\nCommand-3")
print(np.arange(1, 151).reshape(15, -1))


Create an array of shape (15,10):
Command-1
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]

Command-2
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70

Write a NumPy program to create a one dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1.

In [92]:
np.random.seed(10)
print(np.random.rand(40))


[0.771320643266746 0.020751949359402 0.633648234926275 0.748803882538612
 0.49850701230259  0.224796645530848 0.198062864759624 0.760530712198959
 0.169110836562535 0.08833981417401  0.685359818367797 0.953393346194937
 0.003948266327914 0.512192263385777 0.812620961652114 0.612526066829388
 0.7217553174318   0.291876068170633 0.917774122512943 0.714575783397691
 0.542544368011261 0.142170047601527 0.373340760051469 0.674133615066345
 0.441833174422996 0.434013993333294 0.617766978469317 0.513138242554391
 0.650397181931467 0.601038953404544 0.805223196832746 0.521647152393634
 0.908648880808668 0.319236088988545 0.090459349270907 0.300700056636203
 0.11398436186355  0.828681326307677 0.04689631938925  0.626287148311393]


Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [93]:
np.random.seed(20)
cbrt = np.cbrt(7)
nd1 = 200
print(cbrt * np.random.randn(10, 4) + nd1)


[[201.69082669736346 200.3746763082702  200.68394275021677
  195.51750123129818]
 [197.92478991563303 201.07066048488275 201.79714021459858
  198.12823310277952]
 [200.96238963339914 200.77744291067876 200.61875865227867
  199.05613893807728]
 [198.48492638364303 198.38860811141893 197.55239946005003
  200.47003620983824]
 [199.9154583876559  202.99877319355295 202.01069856971475
  200.77735483308504]
 [199.67739161408255 193.89831807071494 202.14273592752286
  202.54951299405823]
 [199.53450968631876 199.75126019761723 199.791457270905
  202.97687756587686]
 [200.24634412660365 196.0460693352411  198.3061125324022
  197.88701546225133]
 [201.7845091237894  203.94032834458278 198.21152802602944
  196.91446071431977]
 [201.0082480992413  197.03285103581035 200.6305276348363
  197.82590294139914]]


Write a NumPy program to generate a uniform, non-uniform random sample from a given 1-D array with and without replacement.

In [94]:
print("Generate a uniform random sample with replacement:")
print(np.random.choice(7, 5))
print("\nGenerate a uniform random sample without replacement:")
print(np.random.choice(7, 5, replace=False))
print("\nGenerate a non-uniform random sample with replacement:")
print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print("\nGenerate a uniform random sample without replacement:")
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))


Generate a uniform random sample with replacement:
[2 2 1 5 2]

Generate a uniform random sample without replacement:
[6 3 5 4 2]

Generate a non-uniform random sample with replacement:
[6 1 6 0 1]

Generate a uniform random sample without replacement:
[1 6 4 3 0]


Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [95]:
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
nums[[0, -1], :] = nums[[-1, 0], :]
print(nums)


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.

In [96]:
nums = np.zeros(shape=(5, 6), dtype='int')
print("Original array:")
print(nums)
nums[::2, ::2] = 3
nums[1::2, ::2] = 7
print("\nNew array:")
print(nums)


Original array:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

New array:
[[3 0 3 0 3 0]
 [7 0 7 0 7 0]
 [3 0 3 0 3 0]
 [7 0 7 0 7 0]
 [3 0 3 0 3 0]]


Write a NumPy program to sort a given array by row and column in ascending order.

In [97]:
nums = np.array([[5.54, 3.38, 7.99],
                 [3.54, 4.38, 6.99],
                 [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
print("\nSort the said array by row in ascending order:")
print(np.sort(nums))
print("\nSort the said array by column in ascending order:")
print(np.sort(nums, axis=0))


Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Sort the said array by row in ascending order:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Sort the said array by column in ascending order:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [98]:
nums = np.array([[5.54, 3.38, 7.99],
                 [3.54, 4.38, 6.99],
                 [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n = 5
print("\nElements of the said array greater than", n)
print(nums[nums > n])
n = 6
print("\nElements of the said array less than", n)
print(nums[nums < n])


Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]


Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number

In [99]:
nums = np.array([[5.54, 3.38, 7.99],
                 [3.54, 8.32, 6.99],
                 [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n = 8.32
r = 18.32
print("\nReplace elements of the said array which are equal to ", n, "with", r)
print(np.where(nums == n, r, nums))
print("\nReplace elements with of the said array which are less than", n, "with", r)
print(np.where(nums < n, r, nums))
print("\nReplace elements with of the said array which are greater than", n, "with", r)
print(np.where(nums > n, r, nums))


Original array:
[[5.54 3.38 7.99]
 [3.54 8.32 6.99]
 [1.54 2.39 9.29]]

Replace elements of the said array which are equal to  8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]

Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]

Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


Write a NumPy program to create an array of equal shape and data type of a given array.

In [100]:
nums = np.array([[5.54, 3.38, 7.99],
                 [3.54, 8.32, 6.99],
                 [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
print("\nNew array of equal shape and data type of the said array filled by 0:")
print(np.zeros_like(nums))


Original array:
[[5.54 3.38 7.99]
 [3.54 8.32 6.99]
 [1.54 2.39 9.29]]

New array of equal shape and data type of the said array filled by 0:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable

In [101]:
nums = np.array([[[1, 5, 2, 1],
                  [4, 3, 5, 6],
                  [6, 3, 0, 6],
                  [7, 3, 5, 0],
                  [2, 3, 3, 5]],

                 [[2, 2, 3, 1],
                  [4, 0, 0, 5],
                  [6, 3, 2, 1],
                  [5, 1, 0, 0],
                  [0, 1, 9, 1]],

                 [[3, 1, 4, 2],
                  [4, 1, 6, 0],
                  [1, 2, 0, 6],
                  [8, 3, 4, 0],
                  [2, 0, 2, 8]]])
print("Array:")
print(nums)


Array:
[[[1 5 2 1]
  [4 3 5 6]
  [6 3 0 6]
  [7 3 5 0]
  [2 3 3 5]]

 [[2 2 3 1]
  [4 0 0 5]
  [6 3 2 1]
  [5 1 0 0]
  [0 1 9 1]]

 [[3 1 4 2]
  [4 1 6 0]
  [1 2 0 6]
  [8 3 4 0]
  [2 0 2 8]]]


Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns. 

In [102]:
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last columns of the said array:")
new_nums = nums[:, ::-1]
print(new_nums)


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last columns of the said array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


 Write a NumPy program to swap rows and columns of a given array in reverse order. 

In [103]:
nums = np.array([[[1, 2, 3, 4],
                  [0, 1, 3, 4],
                  [90, 91, 93, 94],
                  [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print("\nSwap rows and columns of the said array in reverse order:")
new_nums = print(nums[::-1, ::-1])
print(new_nums)


Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]

Swap rows and columns of the said array in reverse order:
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]
None


Write a NumPy program to multiply two given arrays of same size element-by-element. 

In [104]:
nums1 = np.array([[2, 5, 2],
                  [1, 5, 5]])
nums2 = np.array([[5, 3, 4],
                  [3, 2, 5]])
print("Array1:")
print(nums1)
print("Array2:")
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))


Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]
